language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1

matrix:
  fast_finish: true

notifications:
  email: false
addons:
    apt_packages:
        - gfortran
        - hdf5-tools

cache:
    directories:
        - $HOME/.julia

after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("OneClassActiveLearning")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
