language: julia
os:
#  - osx
  - linux
julia:
  - 0.6
#  - 0.7
#  - nightly
notifications:
  email: false
addons:
    apt_packages:
        - gfortran
        - hdf5-tools
script:
    - cd ..
    - git clone https://github.com/englhardt/SVDD.jl.git && cd SVDD.jl
    - julia -e 'Pkg.clone(pwd())'
    - cd ../OneClassActiveLearning.jl
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("OneClassActiveLearning"); Pkg.test("OneClassActiveLearning"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("OneClassActiveLearning")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
